### ISSUE TITLE
Implement proper support for Maya 2023

### ISSUE THREAD

**Issue by SidneyGuenther** [SidneyGuenther/tructure_issues#195]
**Describe the bug**
Currently, the TRUCTURE Maya Menu does not work in Maya.
The MMtoKey Plug isn't working as well.

## ToDo

- [x] figure out wat causes the Menu Loading Issue
- [x] update the Charcoal Editor
- [x] update the MMtoKey Plug-In
