### ISSUE TITLE
Try to convert class method TTProjectItem.meta() into an attribute

### ISSUE THREAD

**Issue by SidneyGuenther** [SidneyGuenther/tructure_issues#86]
### To Do
- [x] convert method to attribute
- [x] convert all occurrences
- [x] check everything for errors
